package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/omnivore-app/omnivore/internal/api/graphql/generated"
	"github.com/omnivore-app/omnivore/internal/api/graphql/model"
	"github.com/omnivore-app/omnivore/internal/api/graphql/scalar"
)

// GoogleLogin is the resolver for the googleLogin field.
func (r *mutationResolver) GoogleLogin(ctx context.Context, input model.GoogleLoginInput) (model.LoginResult, error) {
	panic(fmt.Errorf("not implemented: GoogleLogin - googleLogin"))
}

// GoogleSignup is the resolver for the googleSignup field.
func (r *mutationResolver) GoogleSignup(ctx context.Context, input model.GoogleSignupInput) (model.GoogleSignupResult, error) {
	panic(fmt.Errorf("not implemented: GoogleSignup - googleSignup"))
}

// LogOut is the resolver for the logOut field.
func (r *mutationResolver) LogOut(ctx context.Context) (model.LogOutResult, error) {
	panic(fmt.Errorf("not implemented: LogOut - logOut"))
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, userID string) (model.DeleteAccountResult, error) {
	panic(fmt.Errorf("not implemented: DeleteAccount - deleteAccount"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (model.UpdateUserResult, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, input model.UpdateUserProfileInput) (model.UpdateUserProfileResult, error) {
	panic(fmt.Errorf("not implemented: UpdateUserProfile - updateUserProfile"))
}

// UpdateEmail is the resolver for the updateEmail field.
func (r *mutationResolver) UpdateEmail(ctx context.Context, input model.UpdateEmailInput) (model.UpdateEmailResult, error) {
	panic(fmt.Errorf("not implemented: UpdateEmail - updateEmail"))
}

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, input model.CreateArticleInput) (model.CreateArticleResult, error) {
	panic(fmt.Errorf("not implemented: CreateArticle - createArticle"))
}

// CreateHighlight is the resolver for the createHighlight field.
func (r *mutationResolver) CreateHighlight(ctx context.Context, input model.CreateHighlightInput) (model.CreateHighlightResult, error) {
	panic(fmt.Errorf("not implemented: CreateHighlight - createHighlight"))
}

// MergeHighlight is the resolver for the mergeHighlight field.
func (r *mutationResolver) MergeHighlight(ctx context.Context, input model.MergeHighlightInput) (model.MergeHighlightResult, error) {
	panic(fmt.Errorf("not implemented: MergeHighlight - mergeHighlight"))
}

// UpdateHighlight is the resolver for the updateHighlight field.
func (r *mutationResolver) UpdateHighlight(ctx context.Context, input model.UpdateHighlightInput) (model.UpdateHighlightResult, error) {
	panic(fmt.Errorf("not implemented: UpdateHighlight - updateHighlight"))
}

// DeleteHighlight is the resolver for the deleteHighlight field.
func (r *mutationResolver) DeleteHighlight(ctx context.Context, highlightID string) (model.DeleteHighlightResult, error) {
	panic(fmt.Errorf("not implemented: DeleteHighlight - deleteHighlight"))
}

// UploadFileRequest is the resolver for the uploadFileRequest field.
func (r *mutationResolver) UploadFileRequest(ctx context.Context, input model.UploadFileRequestInput) (model.UploadFileRequestResult, error) {
	panic(fmt.Errorf("not implemented: UploadFileRequest - uploadFileRequest"))
}

// SaveArticleReadingProgress is the resolver for the saveArticleReadingProgress field.
func (r *mutationResolver) SaveArticleReadingProgress(ctx context.Context, input model.SaveArticleReadingProgressInput) (model.SaveArticleReadingProgressResult, error) {
	panic(fmt.Errorf("not implemented: SaveArticleReadingProgress - saveArticleReadingProgress"))
}

// SetBookmarkArticle is the resolver for the setBookmarkArticle field.
func (r *mutationResolver) SetBookmarkArticle(ctx context.Context, input model.SetBookmarkArticleInput) (model.SetBookmarkArticleResult, error) {
	panic(fmt.Errorf("not implemented: SetBookmarkArticle - setBookmarkArticle"))
}

// SetUserPersonalization is the resolver for the setUserPersonalization field.
func (r *mutationResolver) SetUserPersonalization(ctx context.Context, input model.SetUserPersonalizationInput) (model.SetUserPersonalizationResult, error) {
	panic(fmt.Errorf("not implemented: SetUserPersonalization - setUserPersonalization"))
}

// CreateArticleSavingRequest is the resolver for the createArticleSavingRequest field.
func (r *mutationResolver) CreateArticleSavingRequest(ctx context.Context, input model.CreateArticleSavingRequestInput) (model.CreateArticleSavingRequestResult, error) {
	panic(fmt.Errorf("not implemented: CreateArticleSavingRequest - createArticleSavingRequest"))
}

// ReportItem is the resolver for the reportItem field.
func (r *mutationResolver) ReportItem(ctx context.Context, input model.ReportItemInput) (*model.ReportItemResult, error) {
	panic(fmt.Errorf("not implemented: ReportItem - reportItem"))
}

// SetLinkArchived is the resolver for the setLinkArchived field.
func (r *mutationResolver) SetLinkArchived(ctx context.Context, input model.ArchiveLinkInput) (model.ArchiveLinkResult, error) {
	panic(fmt.Errorf("not implemented: SetLinkArchived - setLinkArchived"))
}

// CreateNewsletterEmail is the resolver for the createNewsletterEmail field.
func (r *mutationResolver) CreateNewsletterEmail(ctx context.Context, input *model.CreateNewsletterEmailInput) (model.CreateNewsletterEmailResult, error) {
	panic(fmt.Errorf("not implemented: CreateNewsletterEmail - createNewsletterEmail"))
}

// DeleteNewsletterEmail is the resolver for the deleteNewsletterEmail field.
func (r *mutationResolver) DeleteNewsletterEmail(ctx context.Context, newsletterEmailID string) (model.DeleteNewsletterEmailResult, error) {
	panic(fmt.Errorf("not implemented: DeleteNewsletterEmail - deleteNewsletterEmail"))
}

// SaveURL is the resolver for the saveUrl field.
func (r *mutationResolver) SaveURL(ctx context.Context, input model.SaveURLInput) (model.SaveResult, error) {
	panic(fmt.Errorf("not implemented: SaveURL - saveUrl"))
}

// SavePage is the resolver for the savePage field.
func (r *mutationResolver) SavePage(ctx context.Context, input model.SavePageInput) (model.SaveResult, error) {
	panic(fmt.Errorf("not implemented: SavePage - savePage"))
}

// UpdatePage is the resolver for the updatePage field.
func (r *mutationResolver) UpdatePage(ctx context.Context, input model.UpdatePageInput) (model.UpdatePageResult, error) {
	panic(fmt.Errorf("not implemented: UpdatePage - updatePage"))
}

// SaveFile is the resolver for the saveFile field.
func (r *mutationResolver) SaveFile(ctx context.Context, input model.SaveFileInput) (model.SaveResult, error) {
	panic(fmt.Errorf("not implemented: SaveFile - saveFile"))
}

// SetDeviceToken is the resolver for the setDeviceToken field.
func (r *mutationResolver) SetDeviceToken(ctx context.Context, input model.SetDeviceTokenInput) (model.SetDeviceTokenResult, error) {
	panic(fmt.Errorf("not implemented: SetDeviceToken - setDeviceToken"))
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input model.CreateLabelInput) (model.CreateLabelResult, error) {
	panic(fmt.Errorf("not implemented: CreateLabel - createLabel"))
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, input model.UpdateLabelInput) (model.UpdateLabelResult, error) {
	panic(fmt.Errorf("not implemented: UpdateLabel - updateLabel"))
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id string) (model.DeleteLabelResult, error) {
	panic(fmt.Errorf("not implemented: DeleteLabel - deleteLabel"))
}

// SetLabels is the resolver for the setLabels field.
func (r *mutationResolver) SetLabels(ctx context.Context, input model.SetLabelsInput) (model.SetLabelsResult, error) {
	panic(fmt.Errorf("not implemented: SetLabels - setLabels"))
}

// GenerateAPIKey is the resolver for the generateApiKey field.
func (r *mutationResolver) GenerateAPIKey(ctx context.Context, input model.GenerateAPIKeyInput) (model.GenerateAPIKeyResult, error) {
	panic(fmt.Errorf("not implemented: GenerateAPIKey - generateApiKey"))
}

// Unsubscribe is the resolver for the unsubscribe field.
func (r *mutationResolver) Unsubscribe(ctx context.Context, name string, subscriptionID *string) (model.UnsubscribeResult, error) {
	panic(fmt.Errorf("not implemented: Unsubscribe - unsubscribe"))
}

// Subscribe is the resolver for the subscribe field.
func (r *mutationResolver) Subscribe(ctx context.Context, input model.SubscribeInput) (model.SubscribeResult, error) {
	panic(fmt.Errorf("not implemented: Subscribe - subscribe"))
}

// AddPopularRead is the resolver for the addPopularRead field.
func (r *mutationResolver) AddPopularRead(ctx context.Context, name string) (model.AddPopularReadResult, error) {
	panic(fmt.Errorf("not implemented: AddPopularRead - addPopularRead"))
}

// SaveDiscoverArticle is the resolver for the saveDiscoverArticle field.
func (r *mutationResolver) SaveDiscoverArticle(ctx context.Context, input model.SaveDiscoverArticleInput) (model.SaveDiscoverArticleResult, error) {
	panic(fmt.Errorf("not implemented: SaveDiscoverArticle - saveDiscoverArticle"))
}

// DeleteDiscoverArticle is the resolver for the deleteDiscoverArticle field.
func (r *mutationResolver) DeleteDiscoverArticle(ctx context.Context, input model.DeleteDiscoverArticleInput) (model.DeleteDiscoverArticleResult, error) {
	panic(fmt.Errorf("not implemented: DeleteDiscoverArticle - deleteDiscoverArticle"))
}

// SetWebhook is the resolver for the setWebhook field.
func (r *mutationResolver) SetWebhook(ctx context.Context, input model.SetWebhookInput) (model.SetWebhookResult, error) {
	panic(fmt.Errorf("not implemented: SetWebhook - setWebhook"))
}

// DeleteWebhook is the resolver for the deleteWebhook field.
func (r *mutationResolver) DeleteWebhook(ctx context.Context, id string) (model.DeleteWebhookResult, error) {
	panic(fmt.Errorf("not implemented: DeleteWebhook - deleteWebhook"))
}

// RevokeAPIKey is the resolver for the revokeApiKey field.
func (r *mutationResolver) RevokeAPIKey(ctx context.Context, id string) (model.RevokeAPIKeyResult, error) {
	panic(fmt.Errorf("not implemented: RevokeAPIKey - revokeApiKey"))
}

// SetLabelsForHighlight is the resolver for the setLabelsForHighlight field.
func (r *mutationResolver) SetLabelsForHighlight(ctx context.Context, input model.SetLabelsForHighlightInput) (model.SetLabelsResult, error) {
	panic(fmt.Errorf("not implemented: SetLabelsForHighlight - setLabelsForHighlight"))
}

// MoveLabel is the resolver for the moveLabel field.
func (r *mutationResolver) MoveLabel(ctx context.Context, input model.MoveLabelInput) (model.MoveLabelResult, error) {
	panic(fmt.Errorf("not implemented: MoveLabel - moveLabel"))
}

// SetIntegration is the resolver for the setIntegration field.
func (r *mutationResolver) SetIntegration(ctx context.Context, input model.SetIntegrationInput) (model.SetIntegrationResult, error) {
	panic(fmt.Errorf("not implemented: SetIntegration - setIntegration"))
}

// DeleteIntegration is the resolver for the deleteIntegration field.
func (r *mutationResolver) DeleteIntegration(ctx context.Context, id string) (model.DeleteIntegrationResult, error) {
	panic(fmt.Errorf("not implemented: DeleteIntegration - deleteIntegration"))
}

// OptInFeature is the resolver for the optInFeature field.
func (r *mutationResolver) OptInFeature(ctx context.Context, input model.OptInFeatureInput) (model.OptInFeatureResult, error) {
	panic(fmt.Errorf("not implemented: OptInFeature - optInFeature"))
}

// SetRule is the resolver for the setRule field.
func (r *mutationResolver) SetRule(ctx context.Context, input model.SetRuleInput) (model.SetRuleResult, error) {
	panic(fmt.Errorf("not implemented: SetRule - setRule"))
}

// DeleteRule is the resolver for the deleteRule field.
func (r *mutationResolver) DeleteRule(ctx context.Context, id string) (model.DeleteRuleResult, error) {
	panic(fmt.Errorf("not implemented: DeleteRule - deleteRule"))
}

// SaveFilter is the resolver for the saveFilter field.
func (r *mutationResolver) SaveFilter(ctx context.Context, input model.SaveFilterInput) (model.SaveFilterResult, error) {
	panic(fmt.Errorf("not implemented: SaveFilter - saveFilter"))
}

// DeleteFilter is the resolver for the deleteFilter field.
func (r *mutationResolver) DeleteFilter(ctx context.Context, id string) (model.DeleteFilterResult, error) {
	panic(fmt.Errorf("not implemented: DeleteFilter - deleteFilter"))
}

// MoveFilter is the resolver for the moveFilter field.
func (r *mutationResolver) MoveFilter(ctx context.Context, input model.MoveFilterInput) (model.MoveFilterResult, error) {
	panic(fmt.Errorf("not implemented: MoveFilter - moveFilter"))
}

// UpdateFilter is the resolver for the updateFilter field.
func (r *mutationResolver) UpdateFilter(ctx context.Context, input model.UpdateFilterInput) (model.UpdateFilterResult, error) {
	panic(fmt.Errorf("not implemented: UpdateFilter - updateFilter"))
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (model.CreateGroupResult, error) {
	panic(fmt.Errorf("not implemented: CreateGroup - createGroup"))
}

// Recommend is the resolver for the recommend field.
func (r *mutationResolver) Recommend(ctx context.Context, input model.RecommendInput) (model.RecommendResult, error) {
	panic(fmt.Errorf("not implemented: Recommend - recommend"))
}

// JoinGroup is the resolver for the joinGroup field.
func (r *mutationResolver) JoinGroup(ctx context.Context, inviteCode string) (model.JoinGroupResult, error) {
	panic(fmt.Errorf("not implemented: JoinGroup - joinGroup"))
}

// RecommendHighlights is the resolver for the recommendHighlights field.
func (r *mutationResolver) RecommendHighlights(ctx context.Context, input model.RecommendHighlightsInput) (model.RecommendHighlightsResult, error) {
	panic(fmt.Errorf("not implemented: RecommendHighlights - recommendHighlights"))
}

// LeaveGroup is the resolver for the leaveGroup field.
func (r *mutationResolver) LeaveGroup(ctx context.Context, groupID string) (model.LeaveGroupResult, error) {
	panic(fmt.Errorf("not implemented: LeaveGroup - leaveGroup"))
}

// UploadImportFile is the resolver for the uploadImportFile field.
func (r *mutationResolver) UploadImportFile(ctx context.Context, typeArg model.UploadImportFileType, contentType string) (model.UploadImportFileResult, error) {
	panic(fmt.Errorf("not implemented: UploadImportFile - uploadImportFile"))
}

// MarkEmailAsItem is the resolver for the markEmailAsItem field.
func (r *mutationResolver) MarkEmailAsItem(ctx context.Context, recentEmailID string) (model.MarkEmailAsItemResult, error) {
	panic(fmt.Errorf("not implemented: MarkEmailAsItem - markEmailAsItem"))
}

// ReplyToEmail is the resolver for the replyToEmail field.
func (r *mutationResolver) ReplyToEmail(ctx context.Context, recentEmailID string, reply model.AllowedReply) (model.ReplyToEmailResult, error) {
	panic(fmt.Errorf("not implemented: ReplyToEmail - replyToEmail"))
}

// BulkAction is the resolver for the bulkAction field.
func (r *mutationResolver) BulkAction(ctx context.Context, query string, action model.BulkActionType, labelIds []string, expectedCount *int, async *bool, arguments scalar.JSON) (model.BulkActionResult, error) {
	panic(fmt.Errorf("not implemented: BulkAction - bulkAction"))
}

// ImportFromIntegration is the resolver for the importFromIntegration field.
func (r *mutationResolver) ImportFromIntegration(ctx context.Context, integrationID string) (model.ImportFromIntegrationResult, error) {
	panic(fmt.Errorf("not implemented: ImportFromIntegration - importFromIntegration"))
}

// ExportToIntegration is the resolver for the exportToIntegration field.
func (r *mutationResolver) ExportToIntegration(ctx context.Context, integrationID string) (model.ExportToIntegrationResult, error) {
	panic(fmt.Errorf("not implemented: ExportToIntegration - exportToIntegration"))
}

// SetFavoriteArticle is the resolver for the setFavoriteArticle field.
func (r *mutationResolver) SetFavoriteArticle(ctx context.Context, id string) (model.SetFavoriteArticleResult, error) {
	panic(fmt.Errorf("not implemented: SetFavoriteArticle - setFavoriteArticle"))
}

// UpdateSubscription is the resolver for the updateSubscription field.
func (r *mutationResolver) UpdateSubscription(ctx context.Context, input model.UpdateSubscriptionInput) (model.UpdateSubscriptionResult, error) {
	panic(fmt.Errorf("not implemented: UpdateSubscription - updateSubscription"))
}

// MoveToFolder is the resolver for the moveToFolder field.
func (r *mutationResolver) MoveToFolder(ctx context.Context, id string, folder string) (model.MoveToFolderResult, error) {
	panic(fmt.Errorf("not implemented: MoveToFolder - moveToFolder"))
}

// FetchContent is the resolver for the fetchContent field.
func (r *mutationResolver) FetchContent(ctx context.Context, id string) (model.FetchContentResult, error) {
	panic(fmt.Errorf("not implemented: FetchContent - fetchContent"))
}

// UpdateNewsletterEmail is the resolver for the updateNewsletterEmail field.
func (r *mutationResolver) UpdateNewsletterEmail(ctx context.Context, input model.UpdateNewsletterEmailInput) (model.UpdateNewsletterEmailResult, error) {
	panic(fmt.Errorf("not implemented: UpdateNewsletterEmail - updateNewsletterEmail"))
}

// AddDiscoverFeed is the resolver for the addDiscoverFeed field.
func (r *mutationResolver) AddDiscoverFeed(ctx context.Context, input model.AddDiscoverFeedInput) (model.AddDiscoverFeedResult, error) {
	panic(fmt.Errorf("not implemented: AddDiscoverFeed - addDiscoverFeed"))
}

// DeleteDiscoverFeed is the resolver for the deleteDiscoverFeed field.
func (r *mutationResolver) DeleteDiscoverFeed(ctx context.Context, input model.DeleteDiscoverFeedInput) (model.DeleteDiscoverFeedResult, error) {
	panic(fmt.Errorf("not implemented: DeleteDiscoverFeed - deleteDiscoverFeed"))
}

// EditDiscoverFeed is the resolver for the editDiscoverFeed field.
func (r *mutationResolver) EditDiscoverFeed(ctx context.Context, input model.EditDiscoverFeedInput) (model.EditDiscoverFeedResult, error) {
	panic(fmt.Errorf("not implemented: EditDiscoverFeed - editDiscoverFeed"))
}

// EmptyTrash is the resolver for the emptyTrash field.
func (r *mutationResolver) EmptyTrash(ctx context.Context) (model.EmptyTrashResult, error) {
	panic(fmt.Errorf("not implemented: EmptyTrash - emptyTrash"))
}

// RefreshHome is the resolver for the refreshHome field.
func (r *mutationResolver) RefreshHome(ctx context.Context) (model.RefreshHomeResult, error) {
	panic(fmt.Errorf("not implemented: RefreshHome - refreshHome"))
}

// CreateFolderPolicy is the resolver for the createFolderPolicy field.
func (r *mutationResolver) CreateFolderPolicy(ctx context.Context, input model.CreateFolderPolicyInput) (model.CreateFolderPolicyResult, error) {
	panic(fmt.Errorf("not implemented: CreateFolderPolicy - createFolderPolicy"))
}

// UpdateFolderPolicy is the resolver for the updateFolderPolicy field.
func (r *mutationResolver) UpdateFolderPolicy(ctx context.Context, input model.UpdateFolderPolicyInput) (model.UpdateFolderPolicyResult, error) {
	panic(fmt.Errorf("not implemented: UpdateFolderPolicy - updateFolderPolicy"))
}

// DeleteFolderPolicy is the resolver for the deleteFolderPolicy field.
func (r *mutationResolver) DeleteFolderPolicy(ctx context.Context, id string) (model.DeleteFolderPolicyResult, error) {
	panic(fmt.Errorf("not implemented: DeleteFolderPolicy - deleteFolderPolicy"))
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (model.CreatePostResult, error) {
	panic(fmt.Errorf("not implemented: CreatePost - createPost"))
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (model.UpdatePostResult, error) {
	panic(fmt.Errorf("not implemented: UpdatePost - updatePost"))
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (model.DeletePostResult, error) {
	panic(fmt.Errorf("not implemented: DeletePost - deletePost"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
