package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/omnivore-app/omnivore/internal/api/graphql/generated"
	"github.com/omnivore-app/omnivore/internal/api/graphql/model"
	"github.com/omnivore-app/omnivore/internal/api/graphql/scalar"
)

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID *string, username *string) (model.UserResult, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Article is the resolver for the article field.
func (r *queryResolver) Article(ctx context.Context, username string, slug string, format *string) (model.ArticleResult, error) {
	panic(fmt.Errorf("not implemented: Article - article"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) (model.UsersResult, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// ValidateUsername is the resolver for the validateUsername field.
func (r *queryResolver) ValidateUsername(ctx context.Context, username string) (bool, error) {
	panic(fmt.Errorf("not implemented: ValidateUsername - validateUsername"))
}

// GetUserPersonalization is the resolver for the getUserPersonalization field.
func (r *queryResolver) GetUserPersonalization(ctx context.Context) (model.GetUserPersonalizationResult, error) {
	panic(fmt.Errorf("not implemented: GetUserPersonalization - getUserPersonalization"))
}

// ArticleSavingRequest is the resolver for the articleSavingRequest field.
func (r *queryResolver) ArticleSavingRequest(ctx context.Context, id *string, url *string) (model.ArticleSavingRequestResult, error) {
	panic(fmt.Errorf("not implemented: ArticleSavingRequest - articleSavingRequest"))
}

// NewsletterEmails is the resolver for the newsletterEmails field.
func (r *queryResolver) NewsletterEmails(ctx context.Context) (model.NewsletterEmailsResult, error) {
	panic(fmt.Errorf("not implemented: NewsletterEmails - newsletterEmails"))
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context) (model.LabelsResult, error) {
	panic(fmt.Errorf("not implemented: Labels - labels"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, after *string, first *int, query *string, includeContent *bool, format *string) (model.SearchResult, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// GetDiscoverFeedArticles is the resolver for the getDiscoverFeedArticles field.
func (r *queryResolver) GetDiscoverFeedArticles(ctx context.Context, discoverTopicID string, feedID *string, after *string, first *int) (model.GetDiscoverFeedArticleResults, error) {
	panic(fmt.Errorf("not implemented: GetDiscoverFeedArticles - getDiscoverFeedArticles"))
}

// DiscoverTopics is the resolver for the discoverTopics field.
func (r *queryResolver) DiscoverTopics(ctx context.Context) (model.GetDiscoverTopicResults, error) {
	panic(fmt.Errorf("not implemented: DiscoverTopics - discoverTopics"))
}

// Subscriptions is the resolver for the subscriptions field.
func (r *queryResolver) Subscriptions(ctx context.Context, sort *model.SortParams, typeArg *model.SubscriptionType) (model.SubscriptionsResult, error) {
	panic(fmt.Errorf("not implemented: Subscriptions - subscriptions"))
}

// SendInstallInstructions is the resolver for the sendInstallInstructions field.
func (r *queryResolver) SendInstallInstructions(ctx context.Context) (model.SendInstallInstructionsResult, error) {
	panic(fmt.Errorf("not implemented: SendInstallInstructions - sendInstallInstructions"))
}

// Webhooks is the resolver for the webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context) (model.WebhooksResult, error) {
	panic(fmt.Errorf("not implemented: Webhooks - webhooks"))
}

// Webhook is the resolver for the webhook field.
func (r *queryResolver) Webhook(ctx context.Context, id string) (model.WebhookResult, error) {
	panic(fmt.Errorf("not implemented: Webhook - webhook"))
}

// APIKeys is the resolver for the apiKeys field.
func (r *queryResolver) APIKeys(ctx context.Context) (model.APIKeysResult, error) {
	panic(fmt.Errorf("not implemented: APIKeys - apiKeys"))
}

// TypeaheadSearch is the resolver for the typeaheadSearch field.
func (r *queryResolver) TypeaheadSearch(ctx context.Context, query string, first *int) (model.TypeaheadSearchResult, error) {
	panic(fmt.Errorf("not implemented: TypeaheadSearch - typeaheadSearch"))
}

// UpdatesSince is the resolver for the updatesSince field.
func (r *queryResolver) UpdatesSince(ctx context.Context, after *string, first *int, since scalar.Date, sort *model.SortParams, folder *string) (model.UpdatesSinceResult, error) {
	panic(fmt.Errorf("not implemented: UpdatesSince - updatesSince"))
}

// Integration is the resolver for the integration field.
func (r *queryResolver) Integration(ctx context.Context, name string) (model.IntegrationResult, error) {
	panic(fmt.Errorf("not implemented: Integration - integration"))
}

// Integrations is the resolver for the integrations field.
func (r *queryResolver) Integrations(ctx context.Context) (model.IntegrationsResult, error) {
	panic(fmt.Errorf("not implemented: Integrations - integrations"))
}

// RecentSearches is the resolver for the recentSearches field.
func (r *queryResolver) RecentSearches(ctx context.Context) (model.RecentSearchesResult, error) {
	panic(fmt.Errorf("not implemented: RecentSearches - recentSearches"))
}

// Rules is the resolver for the rules field.
func (r *queryResolver) Rules(ctx context.Context, enabled *bool) (model.RulesResult, error) {
	panic(fmt.Errorf("not implemented: Rules - rules"))
}

// DeviceTokens is the resolver for the deviceTokens field.
func (r *queryResolver) DeviceTokens(ctx context.Context) (model.DeviceTokensResult, error) {
	panic(fmt.Errorf("not implemented: DeviceTokens - deviceTokens"))
}

// Filters is the resolver for the filters field.
func (r *queryResolver) Filters(ctx context.Context) (model.FiltersResult, error) {
	panic(fmt.Errorf("not implemented: Filters - filters"))
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) (model.GroupsResult, error) {
	panic(fmt.Errorf("not implemented: Groups - groups"))
}

// RecentEmails is the resolver for the recentEmails field.
func (r *queryResolver) RecentEmails(ctx context.Context) (model.RecentEmailsResult, error) {
	panic(fmt.Errorf("not implemented: RecentEmails - recentEmails"))
}

// Feeds is the resolver for the feeds field.
func (r *queryResolver) Feeds(ctx context.Context, input model.FeedsInput) (model.FeedsResult, error) {
	panic(fmt.Errorf("not implemented: Feeds - feeds"))
}

// DiscoverFeeds is the resolver for the discoverFeeds field.
func (r *queryResolver) DiscoverFeeds(ctx context.Context) (model.DiscoverFeedResult, error) {
	panic(fmt.Errorf("not implemented: DiscoverFeeds - discoverFeeds"))
}

// ScanFeeds is the resolver for the scanFeeds field.
func (r *queryResolver) ScanFeeds(ctx context.Context, input model.ScanFeedsInput) (model.ScanFeedsResult, error) {
	panic(fmt.Errorf("not implemented: ScanFeeds - scanFeeds"))
}

// Home is the resolver for the home field.
func (r *queryResolver) Home(ctx context.Context, first *int, after *string) (model.HomeResult, error) {
	panic(fmt.Errorf("not implemented: Home - home"))
}

// Subscription is the resolver for the subscription field.
func (r *queryResolver) Subscription(ctx context.Context, id string) (model.SubscriptionResult, error) {
	panic(fmt.Errorf("not implemented: Subscription - subscription"))
}

// HiddenHomeSection is the resolver for the hiddenHomeSection field.
func (r *queryResolver) HiddenHomeSection(ctx context.Context) (model.HiddenHomeSectionResult, error) {
	panic(fmt.Errorf("not implemented: HiddenHomeSection - hiddenHomeSection"))
}

// Highlights is the resolver for the highlights field.
func (r *queryResolver) Highlights(ctx context.Context, after *string, first *int, query *string) (model.HighlightsResult, error) {
	panic(fmt.Errorf("not implemented: Highlights - highlights"))
}

// FolderPolicies is the resolver for the folderPolicies field.
func (r *queryResolver) FolderPolicies(ctx context.Context) (model.FolderPoliciesResult, error) {
	panic(fmt.Errorf("not implemented: FolderPolicies - folderPolicies"))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, userID string, after *string, first *int) (model.PostsResult, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (model.PostResult, error) {
	panic(fmt.Errorf("not implemented: Post - post"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
