package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/omnivore-app/omnivore/internal/api/graphql/generated"
)

// Hello is the resolver for the hello field.
func (r *subscriptionRootTypeResolver) Hello(ctx context.Context) (<-chan *string, error) {
	ch := make(chan *string)
	close(ch)
	return ch, nil
}

// SubscriptionRootType returns generated.SubscriptionRootTypeResolver implementation.
func (r *Resolver) SubscriptionRootType() generated.SubscriptionRootTypeResolver {
	return &subscriptionRootTypeResolver{r}
}

type subscriptionRootTypeResolver struct{ *Resolver }
